version: '3.7'

services:
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    depends_on:
      - prometheus

  owlet:
    build: .
    environment: 
      - OWLET_USER=asdf@asdf.com
      - OWLET_PASS=asdf
    ports:
      - 8000:8000
    depends_on:
      - prometheus
