{
 "title": "Owlet",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Vitals", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Heartbeats per minute",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bpm" } },
   "targets": [
    { "expr": "owlet_heart_rate", "legendFormat": "Baby" }
   ]
  },
  {
   "title": "Heartbeats per minute",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bpm" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "owlet_heart_rate" }
   ]
  },
  {
   "title": "Wiggle Level (movement)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "owlet_wiggle_level", "legendFormat": "Baby" }
   ]
  },
  {
   "title": "Oxygen Level (Spo2)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "owlet_oxygen_level", "legendFormat": "Baby" }
   ]
  },
  {
   "title": "Oxygen Level (Spo2)",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "Sp02%" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "owlet_oxygen_level" }
   ]
  },
  { "title": "API and Technicals", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Base Station On/Off",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "owlet_base_status_on" }
   ]
  },
  {
   "title": "Battery Level",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "owlet_battery_level", "legendFormat": "{{ job }}" }
   ]
  },
  {
   "title": "Battery Level",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "owlet_battery_level", "legendFormat": "{{ job }}" }
   ]
  },
  {
   "title": "API Updates",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "irate(owlet_api_updates_total[1m])",
     "legendFormat": "{{ job }}"
    }
   ]
  }
 ]
}